using InfrastructureApp.Models;
using InfrastructureApp.Services.Minigames;
using InfrastructureApp.ViewModels.Minigames;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace InfrastructureApp.Controllers
{
    [Authorize]
    public class MinigamesController : Controller
    {
        private readonly IMinigameService _minigameService;
        private readonly UserManager<Users> _userManager;

        public MinigamesController(IMinigameService minigameService, UserManager<Users> userManager)
        {
            _minigameService = minigameService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            var statuses = await _minigameService.GetTodayStatusesAsync(userId);
            var currentPoints = await _minigameService.GetCurrentPointsAsync(userId);

            var statusMap = statuses.ToDictionary(status => status.GameKey, status => status);

            var model = new MinigamesIndexViewModel
            {
                CurrentPoints = currentPoints,
                Games = new[]
                {
                    BuildCard(
                        MinigameConstants.SlotsGameKey,
                        "Slots",
                        "Spin three infrastructure symbols generated by the server.",
                        statusMap,
                        isAvailable: true,
                        playUrl: "/Minigames/Slots"),
                    BuildCard(
                        MinigameConstants.MatchingGameKey,
                        "Image Matching",
                        "Match hidden roadwork-themed card pairs. Coming soon in the next slice.",
                        statusMap,
                        isAvailable: false,
                        playUrl: null),
                    BuildCard(
                        MinigameConstants.TriviaGameKey,
                        "Infrastructure Trivia",
                        "Answer short road-safety questions validated by the server. Coming soon.",
                        statusMap,
                        isAvailable: false,
                        playUrl: null),
                    BuildCard(
                        MinigameConstants.TapRepairGameKey,
                        "Tap Repair",
                        "Repair potholes before the timer runs out. Coming soon.",
                        statusMap,
                        isAvailable: false,
                        playUrl: null)
                }
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Slots()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            var statuses = await _minigameService.GetTodayStatusesAsync(userId);
            var slotsStatus = statuses
                .FirstOrDefault(status => status.GameKey == MinigameConstants.SlotsGameKey)
                ?? new MinigameStatus
                {
                    GameKey = MinigameConstants.SlotsGameKey,
                    DailyPointsLimit = MinigameConstants.PointsPerGame
                };

            var model = new SlotsViewModel
            {
                CurrentPoints = await _minigameService.GetCurrentPointsAsync(userId),
                DailyPointsEarned = slotsStatus.DailyPointsEarned,
                HasReachedDailyLimit = slotsStatus.HasReachedDailyLimit,
                PointsAvailable = MinigameConstants.PointsPerGame
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SpinSlots()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            var result = await _minigameService.SpinSlotsAsync(userId);

            return Json(new GameCompletionResultViewModel
            {
                GameKey = result.GameKey,
                AwardedPoints = result.AwardedPoints,
                CurrentPoints = result.CurrentPoints,
                Symbols = result.Symbols,
                IsWinningSpin = result.IsWinningSpin,
                ResultLabel = result.ResultLabel,
                DailyPointsEarned = result.DailyPointsEarned,
                DailyPointsLimit = result.DailyPointsLimit,
                HasReachedDailyLimit = result.HasReachedDailyLimit
            });
        }

        private static MinigameCardViewModel BuildCard(
            string gameKey,
            string name,
            string description,
            IReadOnlyDictionary<string, MinigameStatus> statusMap,
            bool isAvailable,
            string? playUrl)
        {
            var status = statusMap.TryGetValue(gameKey, out var gameStatus)
                ? gameStatus
                : new MinigameStatus
                {
                    GameKey = gameKey,
                    DailyPointsLimit = MinigameConstants.PointsPerGame
                };

            return new MinigameCardViewModel
            {
                GameKey = gameKey,
                Name = name,
                Description = description,
                PointsAvailable = MinigameConstants.PointsPerGame,
                DailyPointsEarned = status.DailyPointsEarned,
                HasReachedDailyLimit = status.HasReachedDailyLimit,
                IsAvailable = isAvailable,
                PlayUrl = playUrl
            };
        }
    }
}
