using InfrastructureApp.Models;
using InfrastructureApp.Services.Minigames;
using InfrastructureApp.ViewModels.Minigames;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace InfrastructureApp.Controllers
{
    [Authorize]
    public class MinigamesController : Controller
    {
        private readonly IMinigameService _minigameService;
        private readonly UserManager<Users> _userManager;

        public MinigamesController(IMinigameService minigameService, UserManager<Users> userManager)
        {
            _minigameService = minigameService;
            _userManager = userManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            var statuses = await _minigameService.GetTodayStatusesAsync(userId);
            var currentPoints = await _minigameService.GetCurrentPointsAsync(userId);

            var statusMap = statuses.ToDictionary(status => status.GameKey, status => status);

            var model = new MinigamesIndexViewModel
            {
                CurrentPoints = currentPoints,
                Games = new[]
                {
                    BuildCard(
                        MinigameConstants.SlotsGameKey,
                        "Slots",
                        "Spin three infrastructure symbols generated by the server.",
                        statusMap,
                        isAvailable: true,
                        playUrl: "/Minigames/Slots"),
                    BuildCard(
                        MinigameConstants.MatchingGameKey,
                        "Image Matching",
                        "Clear the board repeatedly to earn up to 5 points per day.",
                        statusMap,
                        isAvailable: true,
                        playUrl: "/Minigames/Matching"),
                    BuildCard(
                        MinigameConstants.TriviaGameKey,
                        "Infrastructure Trivia",
                        "Answer road-safety questions checked on the server for a daily reward.",
                        statusMap,
                        isAvailable: true,
                        playUrl: "/Minigames/Trivia"),
                    BuildCard(
                        MinigameConstants.TapRepairGameKey,
                        "Tap Repair",
                        "Repair potholes before the timer runs out. Coming soon.",
                        statusMap,
                        isAvailable: false,
                        playUrl: null)
                }
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Slots()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            var statuses = await _minigameService.GetTodayStatusesAsync(userId);
            var slotsStatus = statuses
                .FirstOrDefault(status => status.GameKey == MinigameConstants.SlotsGameKey)
                ?? new MinigameStatus
                {
                    GameKey = MinigameConstants.SlotsGameKey,
                    DailyPointsLimit = MinigameConstants.PointsPerGame
                };

            var model = new SlotsViewModel
            {
                CurrentPoints = await _minigameService.GetCurrentPointsAsync(userId),
                DailyPointsEarned = slotsStatus.DailyPointsEarned,
                HasReachedDailyLimit = slotsStatus.HasReachedDailyLimit,
                PointsAvailable = MinigameConstants.PointsPerGame
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Matching()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            var statuses = await _minigameService.GetTodayStatusesAsync(userId);
            var matchingStatus = statuses
                .FirstOrDefault(status => status.GameKey == MinigameConstants.MatchingGameKey)
                ?? new MinigameStatus
                {
                    GameKey = MinigameConstants.MatchingGameKey,
                    DailyPointsLimit = MinigameConstants.PointsPerGame
                };

            var model = new MatchingViewModel
            {
                CurrentPoints = await _minigameService.GetCurrentPointsAsync(userId),
                DailyPointsEarned = matchingStatus.DailyPointsEarned,
                HasReachedDailyLimit = matchingStatus.HasReachedDailyLimit,
                PointsAvailable = MinigameConstants.PointsPerGame
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Trivia()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            var triviaRound = await _minigameService.GetOrStartTriviaRoundAsync(userId);

            var model = new TriviaViewModel
            {
                CurrentPoints = triviaRound.CurrentPoints,
                DailyPointsEarned = triviaRound.DailyPointsEarned,
                HasReachedDailyLimit = triviaRound.HasReachedDailyLimit,
                PointsAvailable = MinigameConstants.PointsPerGame,
                CorrectAnswers = triviaRound.CorrectAnswers,
                CorrectAnswersToWin = triviaRound.CorrectAnswersToWin,
                IsRoundComplete = triviaRound.IsRoundComplete,
                CurrentQuestion = triviaRound.CurrentQuestion == null
                    ? null
                    : MapTriviaQuestion(triviaRound.CurrentQuestion)
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SpinSlots()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            var result = await _minigameService.SpinSlotsAsync(userId);

            return Json(new GameCompletionResultViewModel
            {
                GameKey = result.GameKey,
                AwardedPoints = result.AwardedPoints,
                CurrentPoints = result.CurrentPoints,
                Symbols = result.Symbols,
                IsWinningSpin = result.IsWinningSpin,
                ResultLabel = result.ResultLabel,
                DailyPointsEarned = result.DailyPointsEarned,
                DailyPointsLimit = result.DailyPointsLimit,
                HasReachedDailyLimit = result.HasReachedDailyLimit
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CompleteGame([FromBody] CompleteGameRequestViewModel request)
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            if (request == null || !MinigameConstants.IsGenericCompletionGameKey(request.GameKey))
            {
                return BadRequest(new { message = "Invalid minigame key." });
            }

            var result = await _minigameService.CompleteGameAsync(userId, request.GameKey);

            return Json(new GameCompletionResultViewModel
            {
                GameKey = result.GameKey,
                AwardedPoints = result.AwardedPoints,
                CurrentPoints = result.CurrentPoints,
                DailyPointsEarned = result.DailyPointsEarned,
                DailyPointsLimit = result.DailyPointsLimit,
                HasReachedDailyLimit = result.HasReachedDailyLimit
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SubmitTrivia([FromBody] SubmitTriviaRequestViewModel request)
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrWhiteSpace(userId))
            {
                return Unauthorized();
            }

            try
            {
                var result = await _minigameService.SubmitTriviaAnswerAsync(
                    userId,
                    new TriviaAnswerSubmission
                    {
                        QuestionId = request?.QuestionId ?? string.Empty,
                        SelectedOptionKey = request?.SelectedOptionKey ?? string.Empty
                    });

                return Json(new GameCompletionResultViewModel
                {
                    GameKey = MinigameConstants.TriviaGameKey,
                    AwardedPoints = result.AwardedPoints,
                    CurrentPoints = result.CurrentPoints,
                    DailyPointsEarned = result.DailyPointsEarned,
                    DailyPointsLimit = result.DailyPointsLimit,
                    HasReachedDailyLimit = result.HasReachedDailyLimit,
                    WasCorrect = result.WasCorrect,
                    CorrectAnswers = result.CorrectAnswers,
                    CorrectAnswersToWin = result.CorrectAnswersToWin,
                    IsRoundComplete = result.IsRoundComplete,
                    NextQuestion = result.NextQuestion == null
                        ? null
                        : MapTriviaQuestion(result.NextQuestion)
                });
            }
            catch (ArgumentException ex)
            {
                return BadRequest(new { message = ex.Message });
            }
        }

        private static MinigameCardViewModel BuildCard(
            string gameKey,
            string name,
            string description,
            IReadOnlyDictionary<string, MinigameStatus> statusMap,
            bool isAvailable,
            string? playUrl)
        {
            var status = statusMap.TryGetValue(gameKey, out var gameStatus)
                ? gameStatus
                : new MinigameStatus
                {
                    GameKey = gameKey,
                    DailyPointsLimit = MinigameConstants.PointsPerGame
                };

            return new MinigameCardViewModel
            {
                GameKey = gameKey,
                Name = name,
                Description = description,
                PointsAvailable = MinigameConstants.PointsPerGame,
                DailyPointsEarned = status.DailyPointsEarned,
                HasReachedDailyLimit = status.HasReachedDailyLimit,
                IsAvailable = isAvailable,
                PlayUrl = playUrl
            };
        }

        private static TriviaQuestionViewModel MapTriviaQuestion(TriviaQuestion question)
        {
            return new TriviaQuestionViewModel
            {
                QuestionId = question.QuestionId,
                Prompt = question.Prompt,
                QuestionType = question.QuestionType,
                TextPlaceholder = question.TextPlaceholder,
                Options = question.Options
                    .Select(option => new TriviaOptionViewModel
                    {
                        OptionKey = option.OptionKey,
                        Label = option.Label
                    })
                    .ToList()
            };
        }
    }
}
